CREATE DATABASE IF NOT EXISTS devbook;
USE devbook;

DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS FOLLOWERS;

CREATE TABLE USERS(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL,
    NICK VARCHAR(50) NOT NULL UNIQUE,
    EMAIL VARCHAR(50) NOT NULL UNIQUE,
    PASSWORD VARCHAR(100) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
) ENGINE=INNODB;

CREATE TABLE FOLLOWERS(
    USER_ID INT NOT NULL,
    FOREIGN KEY (USER_ID)
    REFERENCES USERS(ID)
    ON DELETE CASCADE,

    FOLLOWER_ID INT NOT NULL,
    FOREIGN KEY (FOLLOWER_ID)
    REFERENCES USERS(ID)
    ON DELETE CASCADE,

    PRIMARY KEY(USER_ID, FOLLOWER_ID)
) ENGINE=INNODB;